version: "2.4"
services:
  backend:
    image: ssaas-backend
    build: node
    ports:
      - "3000"
  reverse-proxy:
    build: nginx
    image: ssaas-nginx
    ports:
      - "80:80"
  db:
    build: db
    image: ssaas-db
    ports:
      - "3306"