version: "2.4"
# This docker-compose.yml file does not build anything. It mounts the source code directly into the base image from docker hub.
# It is equivalent to the following docker-run commands:
#     docker volume create nodemodules
#     docker run -it --rm -w /app -v "$PWD:/app" -v "nodemodules:/app/node_modules" -p 3000:3000 node:16-alpine3.14 sh -c "npm i && npm run dev"
services:
  backend:
    image: node:16-alpine3.15
    working_dir: /app
    volumes:
      - "./node:/app"
      - "nodemodules:/app/node_modules"
    ports:
      - "3000"
    command: sh -c "npm i && npm run dev"
  nginx:
    image: nginx:mainline-alpine
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf"
    ports:
      - "8080:80"
volumes:
  nodemodules: